### ISSUE TITLE
Automated Docker container build

### ISSUE THREAD

**Issue by manuguth** [umami-hep/puma#28]
The Docker containers for puma are currently build on [CERN gitlab](https://gitlab.cern.ch/atlas-flavor-tagging-tools/training-images/puma-images) but only via a manual trigger.
We would need to add a web hook which trigger a pipeline on gitlab for each master commit and for the different tags

**Comment by jobirk** [comment]
There is the [GitHub Action](https://github.com/marketplace/actions/build-and-push-docker-images) that should make automatic build and push to Dockerhub quite easy.

We could have something like this:

```yaml
name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: puma:latest
```

If possible I'd build the docker image with buildx such that we also have compatibility for the newer Macbooks which will be more present in HEP in the future I guess.
